name: Cvcoursework2020
channels:
  - defaults
dependencies:
  - python=3.7.1
  - pip
  - pip:
    - matplotlib==3.1.1
    - numpy==1.18.2
    - scipy==1.1.0
    - pandas==0.23.4
    - seaborn==0.10.0
    - torch==1.4.0
    - torchvision==0.5.0
    - facenet-pytorch==2.2.7
    - scikit-learn==0.22.2.post1
    - imgaug==0.4.0
    - opencv-contrib-python==3.4.2.17
    - Pillow==5.3.0
    - imageio==2.4.1
    - joblib==0.13.2
    - jupyter==1.0.0
